name: Deploy Theme

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        
      - name: Install and Build 🔧
        run: |
          rm .gitignore
          mv .gitignore.build .gitignore

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: production # The branch the action should deploy to.
          folder: ./ # The folder the action should deploy.
