name: Adastra Build Theme

on:
  pull_request


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.0

      - name: Run Application
        run: "node app.js"